language: objective-c
osx_image: xcode10

cache: cocoapods
podfile: Podfile

before_script:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - bundle exec pod install

script:
    set -o pipefail && xcodebuild test -verbose -scheme SwiftyHomeTests -destination "platform=iOS Simulator,OS=12.0,name=iPhone X" ONLY_ACTIVE_ARCH=NO | xcpretty
